version: "3.9"

services:
  db:
    image: postgres:16-alpine      # Postgres 16 + vector
    container_name: match-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SQL_HELPERS:/temp/SQL_HELPERS
  api:
    build:
      context: ./Backend/project
      dockerfile: Dockerfile
    container_name: match-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=appdb;Username=app;Password=secret
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
